Repository boostcamp-2020/Project16-A-Account-Book, pull requests merged in 2020-12, with the labels that each got.

#74 MobX Transaction Store 클래스 형태에서 함수형 형태로 수정
  fe/package.json
  fe/src/App.tsx
  fe/src/apis/transaction.ts
  fe/src/pages/MainPage/TransactionDateList.tsx
  fe/src/pages/MainPage/index.tsx
  fe/src/stores/Transaction/index.ts
  fe/src/stores/Transaction/index.tsx
  fe/src/utils/query.test.ts
  fe/src/utils/query.ts
Labels: Front 💖

#83 TransactionAPI year, month를 startDate, endDate로 수정
  be/src/controllers/transaction/index.ts
  be/src/services/transaction/index.ts
Labels: Back 💙

#81 파이차트 SVG 컴포넌트 구현
  fe/src/components/atoms/CircleSvg/index.stories.tsx
  fe/src/components/atoms/CircleSvg/index.tsx
  fe/src/components/molecules/PieChart/index.stories.tsx
  fe/src/components/molecules/PieChart/index.tsx
  fe/src/utils/__tests__/math.test.ts
  fe/src/utils/__tests__/parseDate.test.ts
  fe/src/utils/math.ts
Labels: Front 💖, Molecules

#96 transaction store 구조 변경
  fe/src/stores/Transaction/index.ts
  fe/src/stores/Transaction/index.tsx
  fe/src/types/index.ts
  fe/src/utils/date.ts
Labels: Front 💖

#94 카테고리, 결제수단 조회 API 작성
  be/package.json
  be/src/controllers/category/index.ts
  be/src/controllers/method/index.ts
  be/src/models/account/index.ts
  be/src/routers/api/category/index.ts
  be/src/routers/api/index.ts
  be/src/routers/api/method/index.ts
  be/src/services/category/index.ts
  be/src/services/method/index.ts
  fe/yarn.lock
Labels: Back 💙

#98 Transaction GET API가 accountid 참고해서 가져오도록 수정
  be/src/controllers/transaction/index.ts
  be/src/models/account/index.ts
  be/src/services/transaction/index.ts
Labels: Back 💙

#105 가계부 리스트 페이지 구현
  be/src/controllers/account/index.ts
  be/src/routers/api/account/index.ts
  be/src/routers/api/index.ts
  be/src/seeds/index.ts
  be/src/services/account/index.ts
  be/src/services/transaction/index.ts
  fe/src/App.tsx
  fe/src/apis/account.ts
  fe/src/apis/urls/index.ts
  fe/src/assets/svg/account.svg
  fe/src/components/organisms/Account/index.stories.tsx
  fe/src/components/organisms/Account/index.tsx
  fe/src/components/organisms/Account/style.ts
  fe/src/components/organisms/Calender/index.tsx
  fe/src/components/organisms/HeaderBar/index.tsx
  fe/src/components/organisms/HeaderBar/style.ts
  fe/src/components/organisms/NavBar/index.tsx
  fe/src/components/templates/HeaderNav/index.tsx
  fe/src/pages/AccountListPage/index.stories.tsx
  fe/src/pages/AccountListPage/index.tsx
  fe/src/pages/AuthCheck/index.tsx
  fe/src/pages/CalenderPage/index.tsx
  fe/src/pages/MainPage/index.tsx
  fe/src/stores/Account/index.ts
  fe/src/stores/Transaction/index.ts
  fe/src/styles/GlobalStyle.ts
Labels: Back 💙, Front 💖

#108 필터 UI 구현 및 회원가입 리팩토링 및 default 카테고리, 거래수단 추가
  be/src/models/category/index.ts
  be/src/models/category/static.ts
  be/src/models/method/index.ts
  be/src/models/method/static.ts
  be/src/models/user/index.ts
  be/src/services/auth/index.ts
  fe/package.json
  fe/src/components/atoms/Button/index.stories.tsx
  fe/src/components/atoms/Button/index.tsx
  fe/src/components/atoms/Button/style.ts
  fe/src/components/molecules/DatePicker/index.stories.tsx
  fe/src/components/molecules/DatePicker/index.tsx
  fe/src/components/molecules/DatePicker/style.ts
  fe/src/components/molecules/DateRange/index.stories.tsx
  fe/src/components/molecules/DateRange/index.tsx
  fe/src/components/molecules/DateRange/style.ts
  fe/src/components/molecules/Dropdown/index.stories.tsx
  fe/src/components/molecules/Dropdown/index.tsx
  fe/src/components/molecules/DropdownBody/index.tsx
  fe/src/components/molecules/DropdownBody/style.ts
  fe/src/components/molecules/DropdownHeader/index.tsx
  fe/src/components/molecules/DropdownHeader/style.ts
  fe/src/components/organisms/FilterBar/index.tsx
  fe/src/components/organisms/FilterBar/style.ts
  fe/src/components/organisms/MainFilterForm/CategoryFilterList.tsx
  fe/src/components/organisms/MainFilterForm/FilterListInterface.ts
  fe/src/components/organisms/MainFilterForm/TopFilter.tsx
  fe/src/components/organisms/MainFilterForm/filterReducer.ts
  fe/src/components/organisms/MainFilterForm/index.stories.jsx
  fe/src/components/organisms/MainFilterForm/index.tsx
  fe/src/components/organisms/MainFilterForm/style.ts
  fe/src/components/templates/HeaderNav/style.ts
  fe/src/hooks/useVisible.ts
  fe/src/pages/MainPage/index.stories.tsx
  fe/src/styles/GlobalStyle.ts
  fe/yarn.lock
  package.json
  yarn.lock
Labels: Back 💙, Front 💖

#109 빌드 시 의존성, 절대경로, 환경변수 설정 변경
  be/package.json
  be/src/libs/__tests__/utils.test.ts
  be/webpack.config.js
  be/yarn.lock
Labels: Back 💙, Setting ⚙️

#110 파이차트 페이지 생성
  fe/package.json
  fe/src/App.tsx
  fe/src/apis/category.ts
  fe/src/apis/urls/index.ts
  fe/src/components/atoms/CircleSvg/index.tsx
  fe/src/components/molecules/PieChart/index.stories.tsx
  fe/src/components/molecules/PieChart/index.tsx
  fe/src/components/molecules/PieChartPercent/index.tsx
  fe/src/components/molecules/StatisticsItem/index.stories.tsx
  fe/src/components/molecules/StatisticsItem/index.tsx
  fe/src/components/molecules/StatisticsItem/style.ts
  fe/src/components/organisms/NavBar/index.tsx
  fe/src/components/organisms/PieChartOverview/index.stories.tsx
  fe/src/components/organisms/PieChartOverview/index.tsx
  fe/src/components/organisms/PieChartOverview/style.ts
  fe/src/components/organisms/StatisticsList/index.stories.tsx
  fe/src/components/organisms/StatisticsList/index.tsx
  fe/src/components/templates/MainTemplate/index.stories.tsx
  fe/src/components/templates/MainTemplate/index.tsx
  fe/src/components/templates/MainTemplate/style.ts
  fe/src/hooks/useStatistics.ts
  fe/src/pages/CalenderPage/index.tsx
  fe/src/pages/MainPage/index.tsx
  fe/src/pages/StatisticsPage/index.tsx
  fe/src/stores/Transaction/index.ts
  fe/src/types/index.ts
  fe/yarn.lock
Labels: Front 💖, Pages

#115 MonthInfoHeader에 필요한 수입 지출 calculate로 구하도록 수정
  be/src/services/transaction/index.ts
  fe/src/pages/CalenderPage/index.tsx
  fe/src/pages/MainPage/index.tsx
  fe/src/pages/StatisticsPage/index.tsx
  fe/src/stores/Transaction/index.ts
Labels: Front 💖

#139 하나의 거래내역 가져오는 API 추가
  be/src/app.ts
  be/src/controllers/transaction/index.ts
  be/src/libs/error.ts
  be/src/models/transaction/index.ts
  be/src/models/transaction/static.ts
  be/src/routers/api/transaction/index.ts
  be/src/seeds/transaction.ts
  be/src/services/transaction/index.ts
Labels: Back 💙

#135 프로젝트 라우팅 수정
  be/src/controllers/account/index.ts
  be/src/models/account/index.ts
  be/src/models/account/static.ts
  be/src/models/user/index.ts
  be/src/routers/api/account/index.ts
  be/src/seeds/index.ts
  be/src/seeds/user.ts
  be/src/services/account/index.ts
  be/src/services/auth/index.ts
  fe/src/App.tsx
  fe/src/apis/account.ts
  fe/src/apis/urls/index.ts
  fe/src/components/organisms/NavBar/index.tsx
  fe/src/hooks/useAccountInfo.ts
  fe/src/pages/AccountListPage/index.tsx
  fe/src/pages/AuthCheck/index.tsx
  fe/src/pages/OauthCallbackPage/index.tsx
  fe/src/stores/Account/index.ts
  fe/src/stores/Transaction/index.ts
Labels: Back 💙, Front 💖

#136 달력 페이지에서 한 달력이 데이터가 없을 때 빈 달력 출력하도록 수정 및 빈 페이지 추가
  fe/src/components/organisms/Calender/index.stories.tsx
  fe/src/components/organisms/Calender/index.tsx
  fe/src/components/organisms/CalenderBind/index.stories.tsx
  fe/src/components/organisms/CalenderBind/index.tsx
  fe/src/components/organisms/NoData/index.tsx
  fe/src/components/organisms/NoData/style.ts
  fe/src/pages/CalenderPage/index.tsx
  fe/src/pages/MainPage/index.tsx
  fe/src/utils/date.ts
Labels: Front 💖

#137 Calender오타 Calendar로 변경
  fe/src/App.tsx
  fe/src/components/molecules/CalendarDayBar/index.stories.tsx
  fe/src/components/molecules/CalendarDayBar/index.tsx
  fe/src/components/molecules/CalendarDayBar/style.ts
  fe/src/components/molecules/CalendarOneDate/index.stories.tsx
  fe/src/components/molecules/CalendarOneDate/index.tsx
  fe/src/components/molecules/CalendarOneDate/style.ts
  fe/src/components/molecules/CalendarOneWeek/index.stories.tsx
  fe/src/components/molecules/CalendarOneWeek/index.tsx
  fe/src/components/molecules/CalendarOneWeek/style.ts
  fe/src/components/organisms/Calendar/index.stories.tsx
  fe/src/components/organisms/Calendar/index.tsx
  fe/src/components/organisms/Calendar/style.ts
  fe/src/components/organisms/CalendarBind/index.stories.tsx
  fe/src/components/organisms/CalendarBind/index.tsx
  fe/src/components/organisms/CalendarBind/style.ts
  fe/src/components/organisms/CalenderBind/style.ts
  fe/src/components/organisms/NavBar/index.tsx
  fe/src/pages/CalendarPage/index.stories.tsx
  fe/src/pages/CalendarPage/index.tsx
  fe/src/stores/Transaction/index.ts
Labels: Front 💖, Pages

#142 달력 클릭했을 때 해당하는 데이터를 보여주는 모달 창 나오는 기능 추가
  fe/src/components/molecules/CalendarOneWeek/index.stories.tsx
  fe/src/components/molecules/CalendarOneWeek/index.tsx
  fe/src/components/organisms/Calendar/index.tsx
  fe/src/components/organisms/DateTransactionModal/index.tsx
  fe/src/components/organisms/DateTransactionModal/style.ts
  fe/src/components/organisms/TransactionList/index.stories.tsx
  fe/src/components/organisms/TransactionList/index.tsx
  fe/src/components/organisms/TransactionList/style.ts
  fe/src/components/templates/MainTemplate/index.stories.tsx
  fe/src/pages/CalendarPage/index.tsx
  fe/src/pages/MainPage/TransactionDateList.tsx
  fe/src/stores/Transaction/index.ts
  fe/src/stores/Transaction/transactionStoreUtils.ts
  fe/src/styles/theme.ts
Labels: Front 💖

#157 Transaction 1개 조회, 수정 관련 url 변경
  be/src/.env-template
  be/src/config/index.ts
  be/src/libs/error.ts
  be/src/middlewares/index.ts
  be/src/routers/api/category/index.ts
  be/src/routers/api/index.ts
  be/src/routers/api/method/index.ts
  be/src/routers/api/transaction/index.ts
  be/src/services/auth/index.ts
  fe/src/App.tsx
  fe/src/apis/axios.ts
  fe/src/apis/transaction.ts
  fe/src/apis/urls/index.ts
  fe/src/components/organisms/DateTransactionModal/index.tsx
  fe/src/hooks/useAccountInfo.ts
  fe/src/hooks/useTransactionInput.ts
  fe/src/pages/NotFoundPage/index.tsx
  fe/src/pages/UpdateTransactionPage/index.tsx
Labels: Back 💙, Front 💖, bug 🚨

#158 달력 Modal의 Transaction 클릭 시 수정 페이지로 이동 && Transaction 생성 / 수정 페이지에서 Submit 후 이전 페이지로 이동하게 수정
  fe/src/components/molecules/CalendarOneWeek/index.tsx
  fe/src/components/organisms/DateTransactionModal/index.tsx
  fe/src/pages/CalendarPage/index.tsx
  fe/src/pages/CreateTransactionPage/index.tsx
  fe/src/pages/UpdateTransactionPage/index.tsx
  fe/src/stores/Transaction/index.ts
Labels: Front 💖, bug 🚨

#162 거래내역 삭제 구현
  be/src/controllers/transaction/index.ts
  be/src/routers/api/transaction/index.ts
  be/src/services/transaction/index.ts
  fe/src/apis/transaction.ts
  fe/src/apis/urls/index.ts
  fe/src/assets/svg/trash.svg
  fe/src/components/atoms/Icons/style.ts
  fe/src/components/organisms/HeaderBar/index.tsx
  fe/src/components/organisms/TransactionForm/index.tsx
  fe/src/components/organisms/TransactionForm/style.ts
  fe/src/components/templates/FormTransaction/style.ts
  fe/src/pages/404Page/index.tsx
  fe/src/pages/CreateTransactionPage/index.tsx
  fe/src/pages/UpdateTransactionPage/index.tsx
  fe/src/stores/Transaction/index.ts
Labels: Back 💙, Front 💖

#163 모든 거래내역 가져오는 API 리팩토링
  be/src/controllers/transaction/index.ts
  be/src/models/account/index.ts
  be/src/models/account/static.ts
  be/src/services/transaction/index.ts
Labels: Back 💙, 🌈 Refactor

#164 가계부 생성시 미분류 카테고리 생성
  be/src/models/category/index.ts
  be/src/models/category/static.ts
  fe/package.json
  fe/src/components/organisms/DateTransactionModal/index.tsx
  fe/yarn.lock
Labels: Back 💙, 🌈 Refactor

#161 로그인 한 User에 해당하는 Account만 보이도록 수정
  be/src/controllers/account/index.ts
  be/src/models/account/index.ts
  be/src/services/account/index.ts
  fe/src/stores/Transaction/index.ts
Labels: Back 💙

#168 통계페이지 라인 차트에서 x좌표 간격 수정, y좌표 포맷 수정
  be/src/models/account/static.ts
  fe/src/components/molecules/LineChart/index.tsx
  fe/src/components/organisms/LineChartOverview/index.tsx
Labels: Back 💙, Front 💖

#174 서브헤더바에서 필터링에 맞춰 가격, 날짜 렌더링 & 필터 함수 리팩토링
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/auto-assign.yml
  .prettierrc
  .vscode/settings.json
  README.md
  be/.babelrc
  be/tsconfig.json
  fe/src/components/molecules/DateRange/index.tsx
  fe/src/components/molecules/DateRange/style.ts
  fe/src/components/molecules/TotalBox/index.tsx
  fe/src/components/organisms/DateTransactionModal/index.tsx
  fe/src/components/organisms/LineChartOverview/index.tsx
  fe/src/components/organisms/MonthInfoHeader/MonthInfoHeader.stories.tsx
  fe/src/components/organisms/MonthInfoHeader/index.tsx
  fe/src/components/organisms/MonthInfoHeader/style.ts
  fe/src/components/templates/MainTemplate/index.stories.tsx
  fe/src/pages/CalendarPage/index.tsx
  fe/src/pages/MainPage/TransactionDateList.tsx
  fe/src/pages/MainPage/index.tsx
  fe/src/pages/StatisticsDetailPage/index.tsx
  fe/src/pages/StatisticsPage/index.tsx
  fe/src/stores/Transaction/index.ts
  fe/src/stores/Transaction/transactionStoreUtils.ts
  fe/src/types/index.ts
  fe/src/utils/__tests__/date.test.ts
  fe/src/utils/date.ts
  fe/tsconfig.json
Labels: Front 💖, 🌈 Refactor

#138 카테고리 페이지 생성
  be/package.json
  be/src/app.ts
  be/src/controllers/category/index.ts
  be/src/controllers/method/index.ts
  be/src/libs/error.ts
  be/src/middlewares/index.ts
  be/src/models/account/index.ts
  be/src/models/account/static.ts
  be/src/models/category/index.ts
  be/src/models/method/static.ts
  be/src/routers/api/category/index.ts
  be/src/routers/api/method/index.ts
  be/src/services/category/index.ts
  be/src/services/method/index.ts
  fe/src/apis/category.ts
  fe/src/apis/method.ts
  fe/src/apis/urls/index.ts
  fe/src/components/atoms/EditButton/index.tsx
  fe/src/components/atoms/EditButton/style.ts
  fe/src/components/atoms/Input/index.tsx
  fe/src/components/molecules/CategoryDropdown/index.stories.tsx
  fe/src/components/molecules/CategoryDropdown/index.tsx
  fe/src/components/molecules/CategoryDropdown/style.ts
  fe/src/components/molecules/LabelWrap/index.tsx
  fe/src/components/molecules/LabelWrap/style.ts
  fe/src/components/molecules/Modal/index.tsx
  fe/src/components/molecules/Modal/style.ts
  fe/src/components/molecules/TabHeader/index.tsx
  fe/src/components/molecules/TabHeader/style.ts
  fe/src/components/organisms/CategoryArea/index.stories.tsx
  fe/src/components/organisms/CategoryArea/index.tsx
  fe/src/components/organisms/CategoryArea/style.ts
  fe/src/components/organisms/Header/index.tsx
  fe/src/components/organisms/Header/style.ts
  fe/src/components/organisms/NavBar/index.tsx
  fe/src/components/templates/CategoryTemplate/index.tsx
  fe/src/components/templates/CategoryTemplate/style.ts
  fe/src/pages/CategoryPage/index.tsx
  fe/src/pages/CategoryPage/style.ts
  fe/src/utils/random.ts
Labels: Back 💙, Front 💖, High 🥇

#182 미분류 버그 수정 및 초기 필터 값 생성
  be/src/libs/error.ts
  be/src/middlewares/index.ts
  be/src/models/account/index.ts
  be/src/models/account/static.ts
  be/src/routers/api/category/index.ts
  be/src/routers/api/index.ts
  be/src/routers/api/method/index.ts
  fe/src/components/molecules/InvitationItem/index.stories.tsx
  fe/src/components/molecules/InvitationItem/index.tsx
  fe/src/components/molecules/InvitationItem/style.ts
  fe/src/components/molecules/ModalContainer/index.stories.tsx
  fe/src/components/molecules/ModalContainer/index.tsx
  fe/src/components/molecules/ModalContainer/style.ts
  fe/src/components/organisms/MainFilterForm/index.tsx
  fe/src/components/organisms/TransactionForm/index.tsx
  fe/src/components/organisms/TransactionInputField/index.tsx
  fe/src/stores/Category/index.ts
  fe/src/stores/Method/index.ts
  fe/src/stores/Transaction/index.ts
  fe/src/styles/theme.ts
Labels: Back 💙, Front 💖

#186 모달 컨테이너 컴포넌트 생성
  be/src/middlewares/index.ts
  be/src/models/account/index.ts
  be/src/models/account/static.ts
Labels: Front 💖

#188 알림 목록 리스트 컴포넌트 생성
  fe/src/components/molecules/InvitationItem/style.ts
  fe/src/components/organisms/InvitationList/index.stories.tsx
  fe/src/components/organisms/InvitationList/index.tsx
  fe/src/components/organisms/InvitationList/style.ts
  fe/src/components/organisms/MainFilterForm/index.tsx
Labels: Front 💖, Organisms

#190 가계부 수정 페이지 생성 및 관련 라우팅
  be/src/controllers/user/index.ts
  be/src/libs/error.ts
  be/src/routers/api/index.ts
  be/src/routers/api/user/index.ts
  be/src/services/account/index.ts
  be/src/services/user/index.ts
  fe/src/App.tsx
  fe/src/apis/urls/index.ts
  fe/src/apis/user.ts
  fe/src/assets/svg/person.svg
  fe/src/assets/svg/setting.svg
  fe/src/components/molecules/Dropdown/index.stories.tsx
  fe/src/components/molecules/DropdownBody/index.stories.tsx
  fe/src/components/molecules/DropdownBody/index.tsx
  fe/src/components/molecules/ProfileImgList/index.tsx
  fe/src/components/molecules/ProfileImgList/style.ts
  fe/src/components/molecules/ProfileName/index.stories.tsx
  fe/src/components/molecules/ProfileName/index.tsx
  fe/src/components/molecules/ProfileName/style.ts
  fe/src/components/organisms/Account/index.tsx
  fe/src/components/organisms/Account/style.ts
  fe/src/components/organisms/AccountImageTitleUpdate/index.stories.tsx
  fe/src/components/organisms/AccountImageTitleUpdate/index.tsx
  fe/src/components/organisms/AccountImageTitleUpdate/style.ts
  fe/src/components/organisms/AccountSubmitButtonList/index.stories.tsx
  fe/src/components/organisms/AccountSubmitButtonList/index.tsx
  fe/src/components/organisms/AccountSubmitButtonList/style.ts
  fe/src/components/organisms/InviteUser/index.stories.tsx
  fe/src/components/organisms/InviteUser/index.tsx
  fe/src/components/organisms/InviteUser/style.ts
  fe/src/components/organisms/LineChartOverview/index.tsx
  fe/src/hooks/useInviteUser.ts
  fe/src/pages/AccountListPage/index.tsx
  fe/src/pages/AccountUpdatePage/index.tsx
  fe/src/pages/AuthCheck/index.tsx
  fe/src/pages/OauthCallbackPage/index.tsx
  fe/src/stores/Account/index.ts
  fe/src/types/index.ts
  fe/src/utils/index.ts
  fe/tsconfig.json
Labels: Front 💖

#194 초대된 가계부 조회 API 생성
  be/src/controllers/user/index.ts
  be/src/models/user/index.ts
  be/src/routers/api/user/account.ts
  be/src/routers/api/user/index.ts
  be/src/services/user/index.ts
Labels: Back 💙

#196 초대 된 가계부 리스트 출력
  be/src/services/user/index.ts
  fe/src/apis/urls/index.ts
  fe/src/apis/user.ts
  fe/src/assets/svg/bell.svg
  fe/src/components/molecules/InvitationItem/index.stories.tsx
  fe/src/components/molecules/InvitationItem/index.tsx
  fe/src/components/organisms/HeaderBar/index.tsx
  fe/src/components/organisms/HeaderBar/style.ts
  fe/src/components/organisms/InvitationList/index.stories.tsx
  fe/src/components/organisms/InvitationList/index.tsx
  fe/src/components/organisms/InvitationList/style.ts
  fe/src/components/organisms/MonthInfoHeader/style.ts
  fe/src/components/templates/MainTemplate/style.ts
  fe/src/hooks/useVisible.ts
  fe/src/pages/AccountListPage/index.tsx
Labels: Front 💖

#204 4주차 버그 수정
  be/src/services/category/index.ts
  fe/src/components/molecules/DateRange/style.ts
  fe/src/components/organisms/InvitationList/index.tsx
  fe/src/components/organisms/InvitationList/style.ts
  fe/src/components/organisms/MainFilterForm/index.tsx
  fe/src/components/organisms/TransactionForm/style.ts
  fe/src/components/organisms/TransactionInputField/index.tsx
  fe/src/hooks/useTransactionInput.ts
  fe/src/pages/CategoryPage/index.tsx
  fe/src/pages/CreateTransactionPage/index.tsx
  fe/src/pages/MainPage/index.tsx
  fe/src/pages/StatisticsDetailPage/index.tsx
  fe/src/pages/UpdateTransactionPage/index.tsx
  fe/src/utils/isCanSubmit.ts
  fe/src/utils/validator.ts
Labels: bug 🚨

#210 nginx proxy 설정에 맞게 프로젝트 url 구조 변경
  be/package.json
  be/src/.env-template
  be/src/config/index.ts
  fe/package.json
  fe/src/apis/axios.ts
Labels: Back 💙, Setting ⚙️

#218 파이차트 데이터 없을 경우 화면 & 라인차트 css 수정
  be/src/services/category/index.ts
  fe/src/components/molecules/LineChart/index.tsx
  fe/src/components/molecules/NoDataMessage/index.stories.tsx
  fe/src/components/molecules/NoDataMessage/index.tsx
  fe/src/components/molecules/NoDataMessage/style.ts
  fe/src/components/molecules/NoDataPieChart/index.stories.tsx
  fe/src/components/molecules/NoDataPieChart/index.tsx
  fe/src/components/molecules/NoDataPieChartContents/index.story.tsx
  fe/src/components/molecules/NoDataPieChartContents/index.tsx
  fe/src/components/molecules/NoDataPieChartContents/style.ts
  fe/src/components/organisms/PieChartDetail/index.tsx
  fe/src/components/organisms/PieChartOverview/index.tsx
Labels: Front 💖

#220 카테고리페이지 Tab UI 색상 변경
  fe/src/components/molecules/TabHeader/index.stories.tsx
  fe/src/components/molecules/TabHeader/index.tsx
  fe/src/components/molecules/TabHeader/style.ts
  fe/src/components/organisms/CategoryArea/index.stories.tsx
  fe/src/components/organisms/CategoryArea/index.tsx
  fe/src/pages/CategoryPage/index.tsx
Labels: Front 💖, 🌈 Refactor

#221 달력 시작 요일 설정
  be/src/controllers/user/index.ts
  be/src/routers/api/user/index.ts
  be/src/services/user/index.ts
  fe/src/apis/user.ts
  fe/src/components/atoms/ToggleSwitch/index.stories.tsx
  fe/src/components/atoms/ToggleSwitch/index.tsx
  fe/src/components/atoms/ToggleSwitch/style.ts
  fe/src/components/organisms/HeaderBar/style.ts
  fe/src/pages/AuthCheck/index.tsx
  fe/src/pages/CalendarPage/index.tsx
  fe/src/pages/CalendarPage/styles.ts
Labels: Back 💙, Front 💖

#224 초대 수락/거절 이벤트 생성
  be/src/controllers/category/index.ts
  be/src/controllers/user/index.ts
  be/src/models/user/index.ts
  be/src/routers/api/user/account.ts
  be/src/services/account/index.ts
  be/src/services/category/index.ts
  be/src/services/user/index.ts
  fe/src/apis/urls/index.ts
  fe/src/apis/user.ts
  fe/src/components/atoms/Input/index.tsx
  fe/src/components/organisms/HeaderBar/index.tsx
  fe/src/components/organisms/InvitationList/index.tsx
  fe/src/pages/AccountUpdatePage/index.tsx
Labels: Front 💖

#227 Date Picker Input 길이 수정
  fe/src/components/atoms/DatePicker/style.ts
  fe/src/components/molecules/DateRange/index.tsx
  fe/src/components/molecules/DateRange/style.ts
Labels: Front 💖, bug 🚨

#229 태그 페이지 title 길이 제한 미들웨어 작성 & FE에서 중복 검사 로직 생성
  be/src/controllers/category/index.ts
  be/src/libs/error.ts
  be/src/middlewares/index.ts
  be/src/models/account/index.ts
  be/src/models/account/static.ts
  be/src/routers/api/category/index.ts
  be/src/routers/api/method/index.ts
  be/src/services/category/index.ts
  fe/src/components/molecules/CategoryDropdown/style.ts
  fe/src/pages/CategoryPage/index.tsx
Labels: Back 💙, Front 💖

#234 머지할 때 중괄호 없어졌던 것 수정
  fe/src/apis/user.ts
Labels: Front 💖, bug 🚨

#237 브라우저 재시작 시 가계부 리스트 페이지 렌더링 되지 않는 버그 수정
  fe/src/apis/user.ts
  fe/src/pages/AccountListPage/index.tsx
  fe/src/pages/AuthCheck/index.tsx
Labels: Front 💖, bug 🚨

#242 가계부 생성시 바로 등록되는 버그 수정
  be/src/controllers/account/index.ts
  be/src/services/account/index.ts
Labels: Back 💙, bug 🚨

#244 가계부 수정 시 사용자 목록 초가 되는 버그 수정
  be/src/controllers/account/index.ts
  be/src/services/account/index.ts
Labels: Back 💙, bug 🚨

#247 파이차트 데이터 프론트에서 구하도록 수정 & 미분류 제외한 합계를 통계&달력 서브헤더바에 추가
  be/src/controllers/category/index.ts
  be/src/models/account/index.ts
  be/src/models/account/static.ts
  be/src/routers/api/category/index.ts
  be/src/services/category/index.ts
  be/src/services/category/index.type.ts
  be/src/services/transaction/index.ts
  fe/src/apis/category.ts
  fe/src/apis/urls/index.ts
  fe/src/components/organisms/LineChartOverview/index.tsx
  fe/src/hooks/useStatistics.ts
  fe/src/pages/MainPage/index.tsx
  fe/src/pages/StatisticsDetailPage/index.tsx
  fe/src/pages/StatisticsPage/index.tsx
  fe/src/stores/Transaction/index.ts
  fe/src/stores/Transaction/transactionStoreUtils.ts
  fe/src/stores/__tests__/transaction-data.ts
  fe/src/stores/__tests__/transaction.test.ts
Labels: Back 💙, Front 💖, 🌈 Refactor

#256 MMS 파싱 후 결제수단 추가되도록 변경
  be/src/models/account/index.ts
  be/src/models/account/static.ts
  be/src/services/mms/index.ts
  yarn.lock
Labels: Back 💙, Front 💖, bug 🚨

#260 [FE] Fix: 파이차트 계산할 때, 가격 순으로 내림차순 정렬할 수 있도록 수정
  fe/src/stores/Transaction/index.ts
Labels: Front 💖

#258 가계부 나가기 기능 구현
  be/src/controllers/account/index.ts
  be/src/models/account/index.ts
  be/src/models/account/static.ts
  be/src/routers/api/account/index.ts
  be/src/services/account/index.ts
  fe/src/apis/account.ts
  fe/src/apis/urls/index.ts
  fe/src/components/molecules/CalendarOneDate/style.ts
  fe/src/components/molecules/CalendarOneWeek/style.ts
  fe/src/components/organisms/Calendar/style.ts
  fe/src/pages/AccountUpdatePage/index.tsx
Labels: Back 💙, Front 💖

#264 거래내역 수정시 원래 카테고리, 결제내역을 디폴트로 설정
  fe/src/components/organisms/TransactionInputField/index.tsx
  fe/src/hooks/useTransactionInput.ts
  fe/src/pages/CreateTransactionPage/index.tsx
  fe/src/pages/UpdateTransactionPage/index.tsx
Labels: Front 💖, bug 🚨

#266 달력 미분류 관련 처리 추가 / 메인페이지 Transaction 수입 지출 합 못구하던 것 수정
  fe/src/components/molecules/CalendarOneDate/index.tsx
  fe/src/components/molecules/CalendarOneDate/style.ts
  fe/src/components/molecules/CalendarOneWeek/index.tsx
  fe/src/components/molecules/CalendarOneWeek/style.ts
  fe/src/components/organisms/Calendar/index.tsx
  fe/src/components/organisms/TransactionList/index.tsx
  fe/src/pages/CalendarPage/styles.ts
Labels: Front 💖, bug 🚨

#268 가계부 타이틀 길이 검사 / 중복 검사 기능 추가
  be/src/middlewares/index.ts
  be/src/routers/api/account/index.ts
  be/src/services/account/index.ts
  fe/src/components/organisms/AccountImageTitleUpdate/index.tsx
  fe/src/components/organisms/AccountImageTitleUpdate/style.ts
  fe/src/pages/AccountUpdatePage/index.tsx
  fe/src/stores/Account/index.ts
Labels: Back 💙, Front 💖, bug 🚨

#280 카테고리 탭 type 변경
  fe/package.json
  fe/src/components/molecules/TabHeader/index.tsx
  fe/yarn.lock
Labels: Front 💖, bug 🚨

#304 [BE] Fix: next빠진 것 수정
  be/src/middlewares/index.ts
Labels: Back 💙, bug 🚨

#294 [FE] Refactor : 404페이지 뒤로가기 버튼 추가
  fe/src/pages/NotFoundPage/index.tsx
  fe/src/pages/NotFoundPage/style.ts
Labels: Front 💖, 🌈 Refactor

#295 카테고리 중복 검사 로직 수정
  be/src/controllers/category/index.ts
  be/src/services/category/index.ts
  fe/src/pages/CategoryPage/index.tsx
Labels: Back 💙, Front 💖

#297 모바일에서 Input 클릭 시 zoom-in되는 것 / Datepicker 모바일에서 사용하기 어려웠던 것 수정
  fe/public/index.html
  fe/src/components/atoms/DatePicker/style.ts
  fe/src/components/atoms/Input/style.ts
  fe/src/components/organisms/TransactionInputField/style.ts
  fe/src/styles/GlobalStyle.ts
Labels: Front 💖, bug 🚨

#303 세션 스토리지에 가계부 정보 저장
  fe/src/hooks/useAccountInfo.ts
  fe/src/pages/AccountListPage/index.tsx
Labels: Front 💖

#305 거래내역 폼에서 최대값이 1조 미만 & 거래내역 폼 에러 메시지 수정
  be/src/libs/error.ts
  be/src/middlewares/index.ts
  fe/src/components/atoms/Input/index.tsx
  fe/src/components/atoms/Message/index.stories.tsx
  fe/src/components/atoms/Message/index.tsx
  fe/src/components/atoms/Message/style.ts
  fe/src/components/organisms/TransactionInputField/index.stories.tsx
  fe/src/components/organisms/TransactionInputField/index.tsx
  fe/src/components/organisms/TransactionInputField/style.ts
  fe/src/pages/CreateTransactionPage/index.tsx
  fe/src/pages/UpdateTransactionPage/index.tsx
  fe/src/styles/theme.ts
  fe/src/utils/validator.ts
Labels: Back 💙, Front 💖

#311 가계부 생성/수정 페이지 중복 검사 로직 수정
  be/src/middlewares/index.ts
  be/src/services/account/index.ts
  fe/src/pages/AccountUpdatePage/index.tsx
Labels: Back 💙, Front 💖, bug 🚨

#314 거래처에서 이름 길어졌을 때, ...으로 처리
  fe/src/components/molecules/Transaction/index.tsx
  fe/src/components/molecules/Transaction/style.ts
  package.json
Labels: Front 💖

#313 생성페이지 날짜 선택창 스타일 수정
  fe/src/components/atoms/DatePicker/style.ts
  fe/src/components/molecules/LabelWrap/style.ts
  fe/src/components/organisms/TransactionForm/style.ts
  fe/src/components/organisms/TransactionInputField/index.tsx
Labels: Front 💖

#320 IOS에서 버튼 모양 다른 것 수정
  fe/src/styles/GlobalStyle.ts
Labels: Front 💖, bug 🚨

#324 [FE] Fix : 수정 미들웨어 수정
  be/src/middlewares/index.ts
  fe/src/apis/account.ts
  fe/src/pages/AccountUpdatePage/index.tsx
Labels: Back 💙

#325 [FE] Style : 드랍다운에 폰트 적용
  fe/src/components/organisms/TransactionInputField/style.ts
Labels: Front 💖

#326 [FE] Style : 카테고리 호버 색 추가
  fe/src/components/molecules/CategoryDropdown/style.ts
Labels: Front 💖

#328 [FE] style : datepicker 날짜 가져지는 버그 수정
  fe/src/components/atoms/DatePicker/style.ts
Labels: Front 💖

#336 [FE] Fix: 미분류에서 수정 시 첫 번째 카테고리를 디폴트로 수정
  fe/src/hooks/useTransactionInput.ts
Labels: Front 💖, bug 🚨

#342 통계페이지의 버튼 css 수정 & 타입에 따라 컬러 변경 & 애니메이션 길이 계산 추가
  fe/src/components/molecules/Checkbox/style.ts
  fe/src/components/molecules/LineChart/index.tsx
  fe/src/components/molecules/LineChart/style.ts
  fe/src/components/organisms/PieChartDetail/index.tsx
  fe/src/components/organisms/PieChartDetail/style.ts
  fe/src/components/organisms/PieChartOverview/style.ts
  fe/src/utils/__tests__/math.test.ts
  fe/src/utils/math.ts
Labels: Front 💖

#343 가계부 수정시 소속된 사람들 목록 출력
  fe/src/assets/imgs/more.png
  fe/src/components/molecules/IconText/index.tsx
  fe/src/components/molecules/IconText/style.ts
  fe/src/components/organisms/Account/index.tsx
  fe/src/pages/AccountUpdatePage/index.tsx
  fe/src/pages/AccountUpdatePage/style.ts
Labels: Front 💖

#344 로그인 페이지 생성
  fe/src/components/molecules/CalendarOneDate/index.tsx
  fe/src/components/molecules/CalendarOneDate/style.ts
  fe/src/components/molecules/DropdownHeader/style.ts
  fe/src/components/molecules/GithubButton/index.tsx
  fe/src/components/molecules/GithubButton/style.ts
  fe/src/components/organisms/AccountImageTitleUpdate/style.ts
  fe/src/components/organisms/Calendar/style.ts
  fe/src/components/organisms/CalendarBind/index.tsx
  fe/src/components/organisms/ChattingArea/style.ts
  fe/src/components/organisms/FilterBar/index.tsx
  fe/src/components/organisms/FilterBar/style.ts
  fe/src/components/organisms/MonthInfoHeader/index.tsx
  fe/src/components/templates/LoginTemplate/index.tsx
  fe/src/components/templates/LoginTemplate/style.ts
  fe/src/pages/AccountUpdatePage/index.tsx
  fe/src/pages/CategoryPage/index.tsx
  fe/src/pages/LoginPage/index.tsx
  fe/src/pages/LoginPage/style.ts
  fe/src/stores/Chatting/index.ts
  fe/src/styles/GlobalStyle.ts
Labels: Front 💖, Pages

#345 데이터 없을 때 라인차트 그래프 구현
  fe/src/components/molecules/LineChart/index.tsx
  fe/src/components/organisms/LineChartOverview/index.tsx
Labels: Front 💖

#346 month header바 반응형 구현
  fe/src/components/organisms/MonthInfoHeader/index.tsx
  fe/src/components/organisms/MonthInfoHeader/style.ts
Labels: Front 💖

#349 달력 페이지 모달 깨지는 것 수정 / 달력페이지 CSS 수정 / 헤더바 CSS 추가 / 메인페이지 로딩화면 추가
  fe/src/components/molecules/CalendarOneDate/index.tsx
  fe/src/components/molecules/CalendarOneDate/style.ts
  fe/src/components/organisms/DateTransactionModal/style.ts
  fe/src/components/organisms/HeaderBar/index.tsx
  fe/src/components/organisms/HeaderBar/style.ts
  fe/src/components/organisms/NoData/style.ts
  fe/src/components/templates/MainTemplate/style.ts
  fe/src/pages/AccountListPage/index.tsx
  fe/src/pages/CalendarPage/index.tsx
  fe/src/pages/CalendarPage/styles.ts
  fe/src/pages/CategoryPage/index.tsx
  fe/src/pages/ChattingPage/index.tsx
  fe/src/pages/MainPage/index.tsx
  fe/src/pages/StatisticsDetailPage/index.tsx
  fe/src/pages/StatisticsPage/index.tsx
Labels: Front 💖

#353 [FE] Fix: 가계부 수정 친구 목록 화면 scale하면 화면 넘는 것 수정
  fe/src/components/molecules/IconText/style.ts
Labels: Front 💖, bug 🚨

#354 IOS에서 TransactionHeader에 Undefined가 나오던 것 수정
  fe/src/pages/MainPage/TransactionDateList.tsx
  fe/src/utils/date.ts
Labels: Front 💖, bug 🚨

#355 [FE] Fix: IOS TransactionHeader undefined나오는 문제 수정
  fe/src/pages/MainPage/TransactionDateList.tsx
  fe/src/utils/date.ts
Labels: Front 💖, bug 🚨
